In [1]:
import numpy as np

1. Rosenbrock function

In [2]:
def f(x):
    return 100 * np.power(x[1] - np.power(x[0], 2), 2) + np.power(1 - x[0], 2)

In [3]:
def f_grad(x):
    x1, x2 = x
    grad = np.empty_like(x)
    grad[0] = -400 * x1 * x2 + 400 * np.power(x1, 3) - 2 - 2 * x1
    grad[1] = 200 * x2 - 200 * np.power(x1, 2)
    return grad

In [4]:
def f_hessian(x):
    hessian = np.empty(shape=(2, 2))
    x1, x2 = x
    hessian[0, 0] = -400 * x2 + 1200 * np.power(x1, 2) + 2
    hessian[0, 1] = -400 * x1
    hessian[1, 0] = -400 * x1
    hessian[1, 1] = 200
    return hessian

2. Other function

In [5]:
def g(x):
    x1, x2 = x
    return 150 * np.power(x1 * x2, 2) + np.power(x1/2 + 2 * x2 - 2, 2)

In [6]:
def g_grad(x):
    x1, x2 = x
    grad = np.empty_like(x)
    grad[0] = 300 * x1 * np.power(x2, 2) + (x1 + 4 * x2 - 4) * 0.5
    grad[1] = 300 * x2 * np.power(x1, 2) + (x1 + 4 * x2 - 4) * 2
    return grad

In [12]:
def g_hessian(x):
    hessian = np.empty(shape=(2, 2))
    x1, x2 = x
    hessian[0, 0] = 300 * np.power(x2, 2) + 0.5
    hessian[0, 1] = 600 * x1 * x2 + 2
    hessian[1, 0] = hessian[0, 1]
    hessian[1, 1] = 300 * np.power(x1, 2) + 8
    return hessian

In [8]:
def approximate_gradient(f, x, eps=np.power(1.1e-16, 1/3, dtype='float32')):
    grad = np.empty_like(x)

    for i in range(x.shape[0]):
        ei = np.zeros_like(x)
        ei[i] = eps
        grad[i] = (f(x + ei) - f(x - ei)) / (2 * eps)

    return grad

In [9]:
def approximate_hessian(f, x, eps=np.power(1.1e-16, 1/3, dtype='float32')):
    hessian = np.empty(shape=(x.shape[0], x.shape[0]), dtype=x.dtype)

    for i in range(x.shape[0]):
        for j in range(x.shape[0]):
            ei = np.zeros_like(x)
            ei[i] = eps
            ej = np.zeros_like(x)
            ej[j] = eps
            hessian[i, j] = (f(x + ei + ej) - f(x + ei) - f(x + ej) + f(x)) / np.power(eps, 2)

    return hessian

Rosenbrock function

In [10]:
starting_points = [np.array([1.2, 1.2], dtype='float32'), np.array([-1.2, 1], dtype='float32'), np.array([0.2, 0.8], dtype='float32')]

print("======================================================================")
for x in starting_points:
    x1, x2 = x
    print("Point:", x1, x2)
    print("Exact Calculation:")
    print("f grad(x)", f_grad(x))
    print("f hessian(x)\n", f_hessian(x))
    print("Numerical approximation")
    f_grad_approx = lambda x : approximate_gradient(f, x)
    f_hessian_approx = lambda x : approximate_hessian(f, x)
    print("f grad approximated(x)", f_grad_approx(x))
    print("f hessian approximated(x)\n", f_hessian_approx(x))
    print("Error gradient:", np.linalg.norm(f_grad(x) - f_grad_approx(x)))
    print("Error hessian:", np.linalg.norm(f_hessian(x) - f_hessian_approx(x)))
    print("======================================================================")

Point: 1.2 1.2
Exact Calculation:
f grad(x) [110.80003  -48.000015]
f hessian(x)
 [[1250.00011826 -480.00001907]
 [-480.00001907  200.        ]]
Numerical approximation
f grad approximated(x) [115.04401  -47.769135]
f hessian approximated(x)
 [[1238.0177  -475.39447]
 [-475.39447  198.08067]]
Error gradient: 4.2502484
Error hessian: 13.772593018295234
Point: -1.2 1.0
Exact Calculation:
f grad(x) [-210.80006  -88.00002]
f hessian(x)
 [[1330.00013733  480.00001907]
 [ 480.00001907  200.        ]]
Numerical approximation
f grad approximated(x) [-214.56303   -87.576744]
f hessian approximated(x)
 [[1317.2229   475.39276]
 [ 475.39276  198.0808 ]]
Error gradient: 3.7867014
Error hessian: 14.470479611000002
Point: 0.2 0.8
Exact Calculation:
f grad(x) [-63.2 152. ]
f hessian(x)
 [[-270.00000334  -80.00000119]
 [ -80.00000119  200.        ]]
Numerical approximation
f grad approximated(x) [-62.487984 151.26889 ]
f hessian approximated(x)
 [[-270.75983   -79.728386]
 [ -79.728386  198.08095 ]]
E

In [13]:
starting_points = [np.array([-0.2, 1.2], dtype='float32'), np.array([3.8, 0.1], dtype='float32'), np.array([1.9, 0.6], dtype='float32')]

print("======================================================================")
for x in starting_points:
    x1, x2 = x
    print("Point:", x1, x2)
    print("Exact Calculation:")
    print("f grad(x)", g_grad(x))
    print("f hessian(x)\n", g_hessian(x))
    print("Numerical approximation")
    g_grad_approx = lambda x : approximate_gradient(g, x)
    g_hessian_approx = lambda x : approximate_hessian(g, x)
    print("f grad approximated(x)", g_grad_approx(x))
    print("f hessian approximated(x)\n", g_hessian_approx(x))
    print("Error gradient:", np.linalg.norm(g_grad(x) - g_grad_approx(x)))
    print("Error hessian:", np.linalg.norm(g_hessian(x) - g_hessian_approx(x)))
    print("======================================================================")

Point: -0.2 1.2
Exact Calculation:
f grad(x) [-86.100006  15.600001]
f hessian(x)
 [[ 432.50003433 -142.00000787]
 [-142.00000787   20.00000036]]
Numerical approximation
f grad approximated(x) [-86.2438    15.524965]
f hessian approximated(x)
 [[-4.6298023e+04 -6.9687241e+01]
 [-6.9687241e+01  1.9808064e+01]]
Error gradient: 0.16219223
Error hessian: 46730.63537189417
Point: 3.8 0.1
Exact Calculation:
f grad(x) [ 11.5 433.6]
f hessian(x)
 [[3.50000009e+00 2.30000001e+02]
 [2.30000001e+02 4.33999989e+03]]
Numerical approximation
f grad approximated(x) [ 11.444685 433.64346 ]
f hessian approximated(x)
 [[3.46641111e+00 1.15453156e+02]
 [1.15453156e+02 4.34086865e+03]]
Error gradient: 0.070343904
Error hessian: 161.99603477108425
Point: 1.9 0.6
Exact Calculation:
f grad(x) [205.35002 650.4    ]
f hessian(x)
 [[ 108.50000858  686.0000186 ]
 [ 686.0000186  1090.99997282]]
Numerical approximation
f grad approximated(x) [204.36227 647.2716 ]
f hessian approximated(x)
 [[ 107.45875  340.6987 ]